import { CANVAS } from './Config'
import { FileManager } from './FileManager'
import { py, vh, vw, px } from './utils'

const YELLOW_NOTE = '#fed336'
const BLUE_NOTE = '#00dbff'
const WHITE_NOTE = '#ffffff'
const RED_NOTE = '#ff0000'

export class Skin {
  static config = {}

  static loadConfig () {
    Skin.config = {
      fps: {
        width: 80,
        right: 4,
        bottom: 4,
        height: 28,
        radius: 14,
        font: '微软雅黑',
        fontWeight: 'bold',
        fontSize: 16,
        color: 'rgb(42, 42, 42)',
        background: 'rgb(91, 255, 0)',
      },
      common: {},
      stage: {
        board: {
          background: 'rgba(0, 0, 0, 1)',
        },
        border: {
          width: px(10),
          color: 'rgb(127, 127, 127)',
        },
        columnCenter: CANVAS.WIDTH / 2.0,
        accuracy: {
          x: CANVAS.WIDTH - px(10),
          y: py(106),
          font: `bold ${py(64)}px 微软雅黑`,
          color: '#fff',
          textAlign: 'right',
        },
        ranking: {
          right: px(356),
          top: py(106),
          scale: py(144) / 100,
        },
        combo: {
          assets: null,
          height: 1,
          top: CANVAS.HEIGHT / 1.5,
          font: '微软雅黑',
          fontSize: py(128),
          lineHeight: py(128),
          color: 'rgba(255, 255, 255, 1)',
        },
        judgement: {
          top: CANVAS.HEIGHT / 3,
          effect: {
            defaultMaxScale: py(128) / 100,
            initScale: py(125) / 100,
            initAlpha: 1,
            growTime: 100,
            backTime: 200,
            fadeTime: 1000,
          },
        },
        sectionLine: {
          color: 'rgba(255, 255, 255, 0.8)',
          height: 0,
        },
        hitEffect: {
          speed: {
            rise: py(25),
            fall: py(10),
          },
          height: Math.min(CANVAS.HEIGHT / 2, py(720)),
        },
        score: {
          assets: null,
          right: px(20),
          top: py(10),
          font: '微软雅黑',
          fontWeight: 'bold',
          fontSize: py(96),
          lineHeight: py(96),
          color: 'rgb(255,255,255)',
          strokeColor: 'rgb(34,34,34)',
          textAlign: 'right',
        },
        judgementLine: {
          height: py(200),
        },
        progress: {
          centerX: CANVAS.WIDTH - px(320),
          centerY: py(132),
          radius: py(24),
          lineWidth: py(3),
        },
        keys: {
          keys4: {
            note: {
              width: px(148),
              height: py(64),
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: BLUE_NOTE,
                3: WHITE_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'blue',
              3: 'red',
            },
          },
          keys5: {
            note: {
              width: px(128),
              height: py(60),
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: YELLOW_NOTE,
                3: BLUE_NOTE,
                4: WHITE_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'yellow',
              3: 'blue',
              4: 'red',
            },
          },
          keys6: {
            note: {
              width: px(118),
              height: py(54),
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: WHITE_NOTE,
                3: WHITE_NOTE,
                4: BLUE_NOTE,
                5: WHITE_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'red',
              3: 'red',
              4: 'blue',
              5: 'red',
            },
          },
          keys7: {
            note: {
              width: px(108),
              height: py(48),
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: WHITE_NOTE,
                3: YELLOW_NOTE,
                4: WHITE_NOTE,
                5: BLUE_NOTE,
                6: WHITE_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'red',
              3: 'yellow',
              4: 'red',
              5: 'blue',
              6: 'red',
            },
          },
          keys8: {
            note: {
              width: px(108),
              height: py(48),
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: WHITE_NOTE,
                3: YELLOW_NOTE,
                4: WHITE_NOTE,
                5: BLUE_NOTE,
                6: WHITE_NOTE,
                7: RED_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'red',
              3: 'yellow',
              4: 'red',
              5: 'blue',
              6: 'red',
              7: 'red',
            },
          },
        },
      },
      main: {
        beatmap: {
          item: {
            select: {
              gap: py(20),
              extra: px(200),
              bgColor: 'rgba(255,249,235,0.5)',
              title: {
                color: '#212529',
              },
              left: px(1460),
            },
            hover: {
              gap: py(30),
              extra: px(80),
              bgColor: 'rgba(255,191,128,0.5)',
              title: {
                color: 'rgb(33,37,41)',
              },
              left: px(1480),
            },
            base: {
              gap: py(-12),
              bgColor: 'rgba(255,191,128,0.5)',
              title: {
                color: 'rgb(33,37,41)',
                font: `${py(32)}px 微软雅黑`,
              },
              description: {
                font: `${py(20)}px 微软雅黑`,
              },
              subtitle: {
                font: `bold ${py(24)}px 微软雅黑`,
              },
              width: px(1280),
              height: py(140),
              left: px(1580),
            },
            selectHover: {
              left: px(1380),
            },
            sameGroup: {
              bgColor: 'rgba(140, 217, 242, 0.5)',
            },
            neverPlayed: {
              bgColor: 'rgba(140, 217, 242, 0.5)',
            },
          },
        },
        header: {
          rightHeight: py(160),
          leftHeight: py(260),
          color: 'rgba(255, 255, 255, 1)',
          top: py(20),
          left: py(20),
          title: {
            font: '微软雅黑',
            fontSize: py(40),
            lineHeight: py(48),
            fontWeight: 'normal',
          },
          subtitle: {
            font: '微软雅黑',
            fontSize: py(28),
            lineHeight: py(36),
            fontWeight: 'lighter',
          },
          info1: {
            font: '微软雅黑',
            fontWeight: 'bold',
            fontSize: py(28),
            lineHeight: py(36),
          },
          info2: {
            font: '微软雅黑',
            fontSize: py(28),
            lineHeight: py(36),
            fontWeight: 'lighter',
          },
          difficulty: {
            font: '微软雅黑',
            fontSize: py(16),
            lineHeight: py(24),
            fontWeight: 'normal',
          },
        },
        footer: {
          height: py(162),
          borderWidth: py(6),
          borderColor: 'rgb(0, 102, 255)',
          bgColor: 'rgb(0, 0, 0)',
          menus: {
            left: px(420),
            button: {
              width: px(132),
              gap: px(6),
              outlineColor: 'rgb(115, 115, 115)',
              outlineShadowColor: 'rgb(255, 255, 255)',
              color: 'rgb(255, 255, 255)',
              defaultBgStartColor: 'rgb(57, 57, 57)',
              defaultBgEndColor: 'rgb(31, 31, 31)',
              hoverBorderColor: 'rgb(255, 255, 255)',
            },
          },
        },
      },
      pauseMenu: {
        buttons: {
          base: {
            width: px(600),
            height: py(100),
            top: vh(0.4),
            gap: py(80),
            left: (CANVAS.WIDTH - px(600)) / 2,
            font: '微软雅黑',
            fontSize: py(36),
            radius: 0,
            color: '#fff',
            background: 'rgba(100, 220, 100, 0.85)',
          },
          retry: {
            width: px(600),
            height: py(100),
            gap: py(80),
            left: (CANVAS.WIDTH - px(600)) / 2,
            font: '微软雅黑',
            fontSize: py(36),
            radius: 0,
            color: '#fff',
            background: 'rgba(255, 159, 28, 0.85)',
            text: 'Retry',
          },
          resume: {
            width: px(600),
            height: py(100),
            gap: py(80),
            left: (CANVAS.WIDTH - px(600)) / 2,
            font: '微软雅黑',
            fontSize: py(36),
            radius: 0,
            color: '#fff',
            background: 'rgba(100, 220, 100, 0.85)',
            text: 'Continue',
          },
          back: {
            width: px(600),
            height: py(100),
            gap: py(80),
            left: (CANVAS.WIDTH - px(600)) / 2,
            font: '微软雅黑',
            fontSize: py(36),
            radius: 0,
            color: '#fff',
            text: 'Back to Menu',
            background: 'rgba(255, 100, 100, 0.85)',
          },
        },
        arrow: {
          left: (CANVAS.WIDTH - px(600)) / 2 - px(160),
          right: (CANVAS.WIDTH - px(600)) / 2 - px(160),
          size: py(80),
          color: 'rgba(0,114,254,100)',
        },
      },
      rankingBoard: {
        header: {
          left: 0,
          top: 0,
          width: CANVAS.WIDTH,
          height: py(200),
          background: 'rgba(0, 0, 0, 0.95)',
          info: {
            left: px(20),
            top: py(24),
            title: {
              color: '#fff',
              fontSize: py(48),
              font: '微软雅黑',
              lineHeight: py(64),
            },
            subtitle: {
              color: '#fff',
              fontSize: py(36),
              font: '微软雅黑',
              lineHeight: py(52),
            },
            description: {
              color: '#fff',
              fontSize: py(36),
              font: '微软雅黑',
              lineHeight: py(52),
            },
          },
          label: {
            color: '#fff',
            right: 0,
            top: 0,
            fontSize: py(160),
            font: '微软雅黑',
            lineHeight: py(200),
          },
        },
        score: {
          background: 'rgba(0, 170, 255, 0.6)',
          left: px(40),
          top: py(220),
          radius: py(20),
          height: py(160),
          width: CANVAS.WIDTH / 2 - px(200),
          value: {
            left: px(400),
            top: py(28),
          },
        },
        results: {
          top: py(400),
          left: px(40),
          radius: py(20),
          width: CANVAS.WIDTH / 2 - px(200),
          height: CANVAS.HEIGHT / 2 + py(100),
          background: 'rgba(0, 170, 255, 0.6)',
          judgement: {
            font: '微软雅黑',
            fontWeight: 'bold',
            fontSize: py(88),
            lineHeight: py(88),
            color: '#fff',
            strokeColor: '#222',
            itemLeft: px(40),
            itemValueLeft: px(256),
            itemRight: px(40),
            itemTop: py(38),
            itemHeight: py(132),
          },
          combo: {
            font: '微软雅黑',
            fontWeight: 'bold',
            fontSize: py(88),
            lineHeight: py(88),
            color: '#fff',
            strokeColor: '#222',
            top: py(596),
            itemHeight: py(132),
            itemLeft: px(80),
          },
          accuracy: {
            font: '微软雅黑',
            fontWeight: 'bold',
            fontSize: py(88),
            lineHeight: py(88),
            color: '#fff',
            strokeColor: '#222',
            top: py(596),
            itemHeight: py(132),
            itemLeft: (CANVAS.WIDTH / 2 - px(200)) / 2 + px(80),
          },
        },
        ranking: {
          scale: 2,
          startScale: 8,
          right: px(10),
          top: py(240),
        },
        buttons: {
          retry: {
            width: px(400),
            height: py(100),
            gap: py(80),
            left: CANVAS.WIDTH - px(400) - px(40),
            top: CANVAS.HEIGHT - py(100) - py(20) - py(100) - py(20),
            font: '微软雅黑',
            fontSize: py(36),
            radius: 0,
            color: '#fff',
            background: 'rgba(255, 159, 28, 0.6)',
            hoverBackground: 'rgba(255, 159, 28, 1)',
            text: 'Retry',
          },
          watchReplay: {
            width: px(400),
            height: py(100),
            gap: py(80),
            left: CANVAS.WIDTH - px(400) - px(40),
            top: CANVAS.HEIGHT - py(100) - py(20),
            font: '微软雅黑',
            fontSize: py(36),
            radius: 0,
            color: '#fff',
            background: 'rgba(70, 160, 220, 0.6)',
            hoverBackground: 'rgba(70, 160, 220, 1)',
            text: 'Watch Replay',
          },
          back: {
            width: py(180),
            shortPosition: py(60),
            backDelta: py(15),
            height: py(86),
            gap: 0,
            left: 0,
            top: CANVAS.HEIGHT - py(118),
            font: '微软雅黑',
            fontSize: py(36),
            radius: 0,
            color: '#fff',
            background: 'rgb(238, 52, 153, 1)',
            hoverBackground: 'rgb(187, 16, 118, 1)',
            text: 'back',
            hoverWidth: py(260),
            iconLeft: py(12),
            iconSize: py(32),
          },
        },
      },
    }
  }
}
