import { CANVAS } from './Config'
import { FileManager } from './FileManager'

const note = {
  width: 150,
  height: 50,
  gap: 2,
  color: {
    white: '#ffffff',
    blue: '#00dbff',
  },
}

export class Skin {
  static config = {
    fps: {
      width: 80,
      right: 24,
      bottom: 24,
      height: 28,
      radius: 14,
      font: 'Torus',
      fontWeight: 'normal',
      fontSize: 16,
      color: 'rgb(42, 42, 42)',
      background: 'rgb(91, 255, 0)',
    },
    common: {
      number: {
        width: 36,
        default: {
          ['default-0']: {
            image: FileManager.loadImage('./skin/default-0.png'),
            width: 35,
            height: 52,
          },
          ['default-1']: {
            image: FileManager.loadImage('./skin/default-1.png'),
            width: 25,
            height: 50,
          },
          ['default-2']: {
            image: FileManager.loadImage('./skin/default-2.png'),
            width: 32,
            height: 51,
          },
          ['default-3']: {
            image: FileManager.loadImage('./skin/default-3.png'),
            width: 32,
            height: 52,
          },
          ['default-4']: {
            image: FileManager.loadImage('./skin/default-4.png'),
            width: 36,
            height: 51,
          },
          ['default-5']: {
            image: FileManager.loadImage('./skin/default-5.png'),
            width: 32,
            height: 51,
          },
          ['default-6']: {
            image: FileManager.loadImage('./skin/default-6.png'),
            width: 34,
            height: 52,
          },
          ['default-7']: {
            image: FileManager.loadImage('./skin/default-7.png'),
            width: 32,
            height: 50,
          },
          ['default-8']: {
            image: FileManager.loadImage('./skin/default-8.png'),
            width: 34,
            height: 52,
          },
          ['default-9']: {
            image: FileManager.loadImage('./skin/default-9.png'),
            width: 34,
            height: 52,
          },
        },
      },
    },
    stage: {
      board: {
        bgRgba: 'rgba(0, 0, 0, 1)',
        width: 4 * note.width,
      },
      border: {
        width: 10,
        color: 'rgba(255, 255, 255, 1)',
      },
      columnStart: CANVAS.WIDTH / 2.0 - note.width * 2 - 10,
      accuracy: {
        x: CANVAS.WIDTH - 10,
        y: 140,
        font: 'bold 56px Torus',
        color: '#fff',
        textAlign: 'right',
      },
      ranking: {
        right: 340,
        top: 94,
        scale: 1.44,
      },
      combo: {
        assets: null,
        height: 1,
        top: CANVAS.HEIGHT / 1.5,
      },
      judgement: {
        top: CANVAS.HEIGHT / 3,
        effect: {
          defaultMaxScale: 1.28,
          initScale: 1.25,
          initAlpha: 1,
          growTime: 100,
          backTime: 200,
          fadeTime: 1000,
        },
      },
      note,
      sectionLine: {
        color: 'rgba(255, 255, 255, 0.8)',
        height: 0,
      },
      hitEffect: {
        speed: {
          rise: 25,
          fall: 10,
        },
        height: Math.min(CANVAS.HEIGHT / 2, 540),
      },
      score: {
        assets: null,
        right: 20,
        top: 10,
        font: 'Torus',
        fontWeight: 'bold',
        fontSize: 96,
        lineHeight: 96,
        color: '#fff',
        strokeColor: '#222',
        textAlign: 'right',
      },
      judgementLine: {
        height: 200,
      },
    },
    main: {
      beatmap: {
        item: {
          select: {
            gap: 16,
            extra: 200,
            bgColor: 'rgba(255,249,235,0.5)',
            title: {
              color: '#212529',
            },
          },
          hover: {
            extra: 80,
            gap: 16,
            bgColor: 'rgba(255,191,128,0.5)',
            title: {
              color: '#212529',
            },
          },
          base: {
            height: 160,
            gap: -16,
            bgColor: 'rgba(255,191,128,0.5)',
            title: {
              color: '#212529',
              font: '32px Torus',
            },
            description: {
              font: '20px Torus',
            },
            subtitle: {
              font: 'bold 24px Torus',
            },
          },
          sameGroup: {
            bgColor: 'rgba(140, 217, 242, 0.5)',
          },
          neverPlayed: {
            bgColor: 'rgba(140, 217, 242, 0.5)',
          },
          baseLeft: CANVAS.WIDTH / 2 + 200,
          width: CANVAS.WIDTH,
        },
      },
    },
    pauseMenu: {
      buttons: {
        base: {
          width: 600,
          height: 100,
          gap: 80,
          left: (CANVAS.WIDTH - 600) / 2,
          font: 'Torus',
          fontSize: 36,
          radius: 0,
          color: '#fff',
          background: 'rgba(100, 220, 100, 0.85)',
        },
        retry: {
          width: 600,
          height: 100,
          gap: 80,
          left: (CANVAS.WIDTH - 600) / 2,
          font: 'Torus',
          fontSize: 36,
          radius: 0,
          color: '#fff',
          background: 'rgba(255, 159, 28, 0.85)',
          text: 'Retry',
        },
        resume: {
          width: 600,
          height: 100,
          gap: 80,
          left: (CANVAS.WIDTH - 600) / 2,
          font: 'Torus',
          fontSize: 36,
          radius: 0,
          color: '#fff',
          background: 'rgba(100, 220, 100, 0.85)',
          text: 'Continue',
        },
        back: {
          width: 600,
          height: 100,
          gap: 80,
          left: (CANVAS.WIDTH - 600) / 2,
          font: 'Torus',
          fontSize: 36,
          radius: 0,
          color: '#fff',
          text: 'Back to Menu',
          background: 'rgba(255, 100, 100, 0.85)',
        },
        fullscreen: {
          width: 600,
          height: 100,
          gap: 80,
          left: (CANVAS.WIDTH - 600) / 2,
          font: 'Torus',
          fontSize: 36,
          radius: 0,
          color: '#fff',
          background: 'rgba(255, 255, 255, 0.85)',
          text: 'Enter Fullscreen',
        },
      },
    },
    rankingBoard: {
      header: {
        left: 0,
        top: 0,
        width: CANVAS.WIDTH,
        height: 200,
        background: 'rgba(0, 0, 0, 0.95)',
        info: {
          left: 20,
          top: 24,
          title: {
            color: '#fff',
            fontSize: 48,
            font: 'Torus',
            lineHeight: 64,
          },
          subtitle: {
            color: '#fff',
            fontSize: 36,
            font: 'Torus',
            lineHeight: 52,
          },
          description: {
            color: '#fff',
            fontSize: 36,
            font: 'Torus',
            lineHeight: 52,
          },
        },
        label: {
          color: '#fff',
          right: 0,
          top: 0,
          fontSize: 160,
          font: 'Torus',
          lineHeight: 200,
        },
      },
      score: {
        background: 'rgba(0, 170, 255, 0.6)',
        left: 40,
        top: 220,
        radius: 20,
        height: 160,
        width: CANVAS.WIDTH / 2 - 200,
        value: {
          left: 400,
          top: 28,
        },
      },
      results: {
        top: 400,
        left: 40,
        radius: 20,
        width: CANVAS.WIDTH / 2 - 200,
        height: CANVAS.HEIGHT / 2 + 100,
        background: 'rgba(0, 170, 255, 0.6)',
        judgement: {
          font: 'Torus',
          fontWeight: 'bold',
          fontSize: 88,
          lineHeight: 88,
          color: '#fff',
          strokeColor: '#222',
          itemLeft: 40,
          itemValueLeft: 256,
          itemRight: 40,
          itemTop: 38,
          itemHeight: 132,
        },
        combo: {
          font: 'Torus',
          fontWeight: 'bold',
          fontSize: 88,
          lineHeight: 88,
          color: '#fff',
          strokeColor: '#222',
          top: 596,
          itemHeight: 132,
          itemLeft: 80,
        },
        accuracy: {
          font: 'Torus',
          fontWeight: 'bold',
          fontSize: 88,
          lineHeight: 88,
          color: '#fff',
          strokeColor: '#222',
          top: 596,
          itemHeight: 132,
          itemLeft: (CANVAS.WIDTH / 2 - 200) / 2 + 80,
        },
      },
      ranking: {
        scale: 2,
        startScale: 8,
        right: 10,
        top: 240,
      },
      buttons: {
        retry: {
          width: 400,
          height: 100,
          gap: 80,
          left: CANVAS.WIDTH - 400 - 40,
          top: CANVAS.HEIGHT - 120,
          font: 'Torus',
          fontSize: 36,
          radius: 0,
          color: '#fff',
          background: 'rgba(255, 159, 28, 0.6)',
          hoverBackground: 'rgba(255, 159, 28, 1)',
          text: 'Retry',
        },
        watchReplay: {
          width: 400,
          height: 100,
          gap: 80,
          left: CANVAS.WIDTH - 400 - 40,
          top: CANVAS.HEIGHT,
          font: 'Torus',
          fontSize: 36,
          radius: 0,
          color: '#fff',
          background: 'rgba(70, 160, 220, 0.6)',
          hoverBackground: 'rgba(70, 160, 220, 1)',
          text: 'Watch Replay',
        },
        back: {
          width: 200,
          height: 100,
          gap: 80,
          left: 0,
          top: CANVAS.HEIGHT - 20,
          font: 'Torus',
          fontSize: 36,
          radius: 0,
          color: '#fff',
          background: 'rgba(255, 100, 150, 1)',
          text: 'Back',
          hoverWidth: 300,
        },
      },
    },
  }

  static loadConfig (config) {
    Skin.config = {
      ...Skin.config,
      config,
    }
  }
}
