import { CANVAS } from './Config'
import { FileManager } from './FileManager'

const YELLOW_NOTE = '#fed336'
const BLUE_NOTE = '#00dbff'
const WHITE_NOTE = '#ffffff'
const RED_NOTE = '#ff0000'

export class Skin {
  static config = {}

  static loadConfig () {
    Skin.config = {
      fps: {
        width: 80,
        right: 24,
        bottom: 24,
        height: 28,
        radius: 14,
        font: '微软雅黑',
        fontWeight: 'bold',
        fontSize: 16,
        color: 'rgb(42, 42, 42)',
        background: 'rgb(91, 255, 0)',
      },
      common: {
        number: {
          width: 36,
          default: {
            ['default-0']: {
              image: FileManager.loadImage('./skin/default-0.png'),
              width: 35,
              height: 52,
            },
            ['default-1']: {
              image: FileManager.loadImage('./skin/default-1.png'),
              width: 25,
              height: 50,
            },
            ['default-2']: {
              image: FileManager.loadImage('./skin/default-2.png'),
              width: 32,
              height: 51,
            },
            ['default-3']: {
              image: FileManager.loadImage('./skin/default-3.png'),
              width: 32,
              height: 52,
            },
            ['default-4']: {
              image: FileManager.loadImage('./skin/default-4.png'),
              width: 36,
              height: 51,
            },
            ['default-5']: {
              image: FileManager.loadImage('./skin/default-5.png'),
              width: 32,
              height: 51,
            },
            ['default-6']: {
              image: FileManager.loadImage('./skin/default-6.png'),
              width: 34,
              height: 52,
            },
            ['default-7']: {
              image: FileManager.loadImage('./skin/default-7.png'),
              width: 32,
              height: 50,
            },
            ['default-8']: {
              image: FileManager.loadImage('./skin/default-8.png'),
              width: 34,
              height: 52,
            },
            ['default-9']: {
              image: FileManager.loadImage('./skin/default-9.png'),
              width: 34,
              height: 52,
            },
          },
        },
      },
      stage: {
        board: {
          background: 'rgba(0, 0, 0, 1)',
        },
        border: {
          width: 10,
          color: 'rgb(127, 127, 127)',
        },
        columnCenter: CANVAS.WIDTH / 2.0,
        accuracy: {
          x: CANVAS.WIDTH - 10,
          y: 128,
          font: 'bold 56px 微软雅黑',
          color: '#fff',
          textAlign: 'right',
        },
        ranking: {
          right: 340,
          top: 94,
          scale: 1.44,
        },
        combo: {
          assets: null,
          height: 1,
          top: CANVAS.HEIGHT / 1.5,
          font: '微软雅黑',
          fontSize: 128,
          lineHeight: 128,
          color: 'rgba(255, 255, 255, 1)',
        },
        judgement: {
          top: CANVAS.HEIGHT / 3,
          effect: {
            defaultMaxScale: 1.28,
            initScale: 1.25,
            initAlpha: 1,
            growTime: 100,
            backTime: 200,
            fadeTime: 1000,
          },
        },
        sectionLine: {
          color: 'rgba(255, 255, 255, 0.8)',
          height: 0,
        },
        hitEffect: {
          speed: {
            rise: 25,
            fall: 10,
          },
          height: Math.min(CANVAS.HEIGHT / 2, 720),
        },
        score: {
          assets: null,
          right: 20,
          top: 10,
          font: '微软雅黑',
          fontWeight: 'bold',
          fontSize: 96,
          lineHeight: 96,
          color: '#fff',
          strokeColor: '#222',
          textAlign: 'right',
        },
        judgementLine: {
          height: 200,
        },
        keys: {
          keys4: {
            note: {
              width: 148,
              height: 64,
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: BLUE_NOTE,
                3: WHITE_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'blue',
              3: 'red',
            },
          },
          keys5: {
            note: {
              width: 128,
              height: 60,
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: YELLOW_NOTE,
                3: BLUE_NOTE,
                4: WHITE_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'yellow',
              3: 'blue',
              4: 'red',
            },
          },
          keys6: {
            note: {
              width: 118,
              height: 54,
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: WHITE_NOTE,
                3: WHITE_NOTE,
                4: BLUE_NOTE,
                5: WHITE_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'red',
              3: 'red',
              4: 'blue',
              5: 'red',
            },
          },
          keys7: {
            note: {
              width: 108,
              height: 48,
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: WHITE_NOTE,
                3: YELLOW_NOTE,
                4: WHITE_NOTE,
                5: BLUE_NOTE,
                6: WHITE_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'red',
              3: 'yellow',
              4: 'red',
              5: 'blue',
              6: 'red',
            },
          },
          keys8: {
            note: {
              width: 150,
              height: 50,
              gap: 0,
              color: {
                0: WHITE_NOTE,
                1: BLUE_NOTE,
                2: WHITE_NOTE,
                3: YELLOW_NOTE,
                4: WHITE_NOTE,
                5: BLUE_NOTE,
                6: WHITE_NOTE,
                7: RED_NOTE,
              },
            },
            hitEffect: {
              0: 'red',
              1: 'blue',
              2: 'red',
              3: 'yellow',
              4: 'red',
              5: 'blue',
              6: 'red',
              7: 'red',
            },
          },
        },
      },
      main: {
        beatmap: {
          item: {
            select: {
              gap: 16,
              extra: 200,
              bgColor: 'rgba(255,249,235,0.5)',
              title: {
                color: '#212529',
              },
            },
            hover: {
              extra: 80,
              gap: 16,
              bgColor: 'rgba(255,191,128,0.5)',
              title: {
                color: '#212529',
              },
            },
            base: {
              height: 160,
              gap: -16,
              bgColor: 'rgba(255,191,128,0.5)',
              title: {
                color: '#212529',
                font: '32px 微软雅黑',
              },
              description: {
                font: '20px 微软雅黑',
              },
              subtitle: {
                font: 'bold 24px 微软雅黑',
              },
            },
            sameGroup: {
              bgColor: 'rgba(140, 217, 242, 0.5)',
            },
            neverPlayed: {
              bgColor: 'rgba(140, 217, 242, 0.5)',
            },
            baseLeft: CANVAS.WIDTH / 2 + 200,
            width: CANVAS.WIDTH,
          },
        },
      },
      pauseMenu: {
        buttons: {
          base: {
            width: 600,
            height: 100,
            gap: 80,
            left: (CANVAS.WIDTH - 600) / 2,
            font: '微软雅黑',
            fontSize: 36,
            radius: 0,
            color: '#fff',
            background: 'rgba(100, 220, 100, 0.85)',
          },
          retry: {
            width: 600,
            height: 100,
            gap: 80,
            left: (CANVAS.WIDTH - 600) / 2,
            font: '微软雅黑',
            fontSize: 36,
            radius: 0,
            color: '#fff',
            background: 'rgba(255, 159, 28, 0.85)',
            text: 'Retry',
          },
          resume: {
            width: 600,
            height: 100,
            gap: 80,
            left: (CANVAS.WIDTH - 600) / 2,
            font: '微软雅黑',
            fontSize: 36,
            radius: 0,
            color: '#fff',
            background: 'rgba(100, 220, 100, 0.85)',
            text: 'Continue',
          },
          back: {
            width: 600,
            height: 100,
            gap: 80,
            left: (CANVAS.WIDTH - 600) / 2,
            font: '微软雅黑',
            fontSize: 36,
            radius: 0,
            color: '#fff',
            text: 'Back to Menu',
            background: 'rgba(255, 100, 100, 0.85)',
          },
          fullscreen: {
            width: 600,
            height: 100,
            gap: 80,
            left: (CANVAS.WIDTH - 600) / 2,
            font: '微软雅黑',
            fontSize: 36,
            radius: 0,
            color: '#fff',
            background: 'rgba(255, 255, 255, 0.85)',
            text: 'Enter Fullscreen',
          },
        },
        arrow: {
          left: (CANVAS.WIDTH - 600) / 2 - 160,
          right: (CANVAS.WIDTH - 600) / 2 - 160,
          size: 80,
          color: 'rgba(0,114,254,100)',
        },
      },
      rankingBoard: {
        header: {
          left: 0,
          top: 0,
          width: CANVAS.WIDTH,
          height: 200,
          background: 'rgba(0, 0, 0, 0.95)',
          info: {
            left: 20,
            top: 24,
            title: {
              color: '#fff',
              fontSize: 48,
              font: '微软雅黑',
              lineHeight: 64,
            },
            subtitle: {
              color: '#fff',
              fontSize: 36,
              font: '微软雅黑',
              lineHeight: 52,
            },
            description: {
              color: '#fff',
              fontSize: 36,
              font: '微软雅黑',
              lineHeight: 52,
            },
          },
          label: {
            color: '#fff',
            right: 0,
            top: 0,
            fontSize: 160,
            font: '微软雅黑',
            lineHeight: 200,
          },
        },
        score: {
          background: 'rgba(0, 170, 255, 0.6)',
          left: 40,
          top: 220,
          radius: 20,
          height: 160,
          width: CANVAS.WIDTH / 2 - 200,
          value: {
            left: 400,
            top: 28,
          },
        },
        results: {
          top: 400,
          left: 40,
          radius: 20,
          width: CANVAS.WIDTH / 2 - 200,
          height: CANVAS.HEIGHT / 2 + 100,
          background: 'rgba(0, 170, 255, 0.6)',
          judgement: {
            font: '微软雅黑',
            fontWeight: 'bold',
            fontSize: 88,
            lineHeight: 88,
            color: '#fff',
            strokeColor: '#222',
            itemLeft: 40,
            itemValueLeft: 256,
            itemRight: 40,
            itemTop: 38,
            itemHeight: 132,
          },
          combo: {
            font: '微软雅黑',
            fontWeight: 'bold',
            fontSize: 88,
            lineHeight: 88,
            color: '#fff',
            strokeColor: '#222',
            top: 596,
            itemHeight: 132,
            itemLeft: 80,
          },
          accuracy: {
            font: '微软雅黑',
            fontWeight: 'bold',
            fontSize: 88,
            lineHeight: 88,
            color: '#fff',
            strokeColor: '#222',
            top: 596,
            itemHeight: 132,
            itemLeft: (CANVAS.WIDTH / 2 - 200) / 2 + 80,
          },
        },
        ranking: {
          scale: 2,
          startScale: 8,
          right: 10,
          top: 240,
        },
        buttons: {
          retry: {
            width: 400,
            height: 100,
            gap: 80,
            left: CANVAS.WIDTH - 400 - 40,
            top: CANVAS.HEIGHT - 100 - 20 - 100 - 20,
            font: '微软雅黑',
            fontSize: 36,
            radius: 0,
            color: '#fff',
            background: 'rgba(255, 159, 28, 0.6)',
            hoverBackground: 'rgba(255, 159, 28, 1)',
            text: 'Retry',
          },
          watchReplay: {
            width: 400,
            height: 100,
            gap: 80,
            left: CANVAS.WIDTH - 400 - 40,
            top: CANVAS.HEIGHT - 100 - 20,
            font: '微软雅黑',
            fontSize: 36,
            radius: 0,
            color: '#fff',
            background: 'rgba(70, 160, 220, 0.6)',
            hoverBackground: 'rgba(70, 160, 220, 1)',
            text: 'Watch Replay',
          },
          back: {
            width: 180,
            shortPosition: 60,
            backDelta: 15,
            height: 86,
            gap: 0,
            left: 0,
            top: CANVAS.HEIGHT - 86 - 32,
            font: '微软雅黑',
            fontSize: 36,
            radius: 0,
            color: '#fff',
            background: 'rgb(238, 52, 153, 1)',
            hoverBackground: 'rgb(187, 16, 118, 1)',
            text: 'Back',
            hoverWidth: 260,
            iconLeft: 12,
            iconSize: 32,
          },
        },
      },
    }
  }
}
